### PR TITLE
Added record deserialization, which implies java 16 codebase

### PR DESCRIPTION
**Pull request by reuschling**
Hello,

I added support for correct java Records de-serialization, as I mentioned [here](https://github.com/jdereg/json-io/issues/151).

These are the changes I made:
* pom.xml: Switched to a more recent version of the groovy-compiler which supports also Java 16. This one is sadly not in maven central yet, so I added the groovy repo as additional maven source
* Added a new check in Resolver.java whether the current object is a Record (as it is currently with enums). The check is with class.isRecord() which was added at Java 16, thus the need of Java 16 codebase
* Added a method getRecord(..) that creates the final Record Object. As Records are immutable, Record creation can only be done by passing the parameters to the constructor. The method makes sure that the parameter order is correct
* Still after Object creation, json-io tried to set the parameters, which is not possible on the final, immutable Record members. Thus, I added a simple anonymous base reader in JsonReader.java that simply returns our yet finished Object
* For compilation of some groovy tests in Intellij Idea, I had to add some casts to get no compilation errors with the new compiler setting. This was strange for me as non-groovy developer, as compilation with maven in the shell was fine. 
* Added a new small test class 'TestRecords.java' to test the functionality

I know it would be an issue if json-io is only usable with java code>=16. Maybe there exists a workaround with reflections, or even better with a [multi release jar](https://www.baeldung.com/java-multi-release-jar#mrjar) (also nice with [maven](https://baeldung-cn.com/maven-multi-release-jars)).  Nevertheless this would be one working solution for supporting java records.

### CODE REVIEW

**Comment by jdereg** [comment]
This should be doable without modifying json-io. If you write a custom
reader/writer, ans add in an instantiate, you should be good to go with any
Java version. Look at the 'Customization' section of the User Guide.

**Comment by jdereg** [comment]
The @type written in the .json is how json-io knows what "specific type" of
Record to instantiate.  The JsonObject that represents the "to be read in"
object has this as a member variable on it.

Normally, to add a new type of class to json-io that needs specifical
handling, the Readers.java and Writers.java have the appropriate reader and
writer added.  The appropriate instantiator is then added.  In this case,
it sounds like the "fill in the object" step is failing, which is not
currently a "pluggable" part of json-io.  That would be the idea fix.  A
custom "filler" would be added for those classes that throw an exception
when they are attempting to be reflectively stuffed.

Does this make sense?  It could help guide your changes to not only solve
the Record class you mention (new RecordReader and RecordWriter added) but
also a "fill()" API added that is called after instantiation (if the class
is in the "filler" classes list).   What do you think?

**Comment by reuschling** [comment]
To be honest, I'm not really sure about the distinction of the custom `Reader` and the `Instantiator`
* Reader: Creates the final object, it will not be filled up anymore by json-io, but you can fill it on your own which is nice. It triggers also by specifying an upper class... I was wrong that the current type was not available there, I missed the `getType` method. So writing a general reader for records is possible.
* Instantiator: Creates the object, but it is filled up from json-io, which is not possible because of the final members of records. But if you want to have both, you can write a reader.

Here is the code of a running general-purpose reader that works for all records, by instantiation over JsonObject.getType:

```java
record TestRecord(String strCheck, boolean bCheck) {}

JsonReader.addReaderPermanent(Record.class, new JsonReader.JsonClassReaderEx()
{
    @Override
    public Object read(Object jOb, Deque<JsonObject<String, Object>> stack, Map<String, Object> args)
    {
        try
        {
            JsonObject jsonObj = (JsonObject) jOb;
            ArrayList<Class> lParameterTypes = new ArrayList<>(jsonObj.size());
            ArrayList<Object> lParameterValues = new ArrayList<>(jsonObj.size());

            Class c = Class.forName(jsonObj.getType());
            // the record components are per definition in the constructor parameter order
            for (RecordComponent recordComponent : c.getRecordComponents())
            {
                lParameterTypes.add(recordComponent.getType());
                lParameterValues.add(jsonObj.get(recordComponent.getName()));
            }

            Constructor constructor = c.getDeclaredConstructor(lParameterTypes.toArray(new Class[0]));

            return constructor.newInstance(lParameterValues.toArray(new Object[0]));

        } catch (Exception e)
        {
            throw new RuntimeException(e);
        }
    }
});


TestRecord rec = new TestRecord("check", false);
String strJson = JsonWriter.objectToJson(rec);

TestRecord clone = (TestRecord) JsonReader.jsonToJava(strJson);
```

To support this in json-io without changing the codebase to java 16, the problematic invocations with RecordComponent could be done over reflection. What do you think about it?

**Comment by reuschling** [comment]
I changed my pull request to simply add a `RecordReader` inside `Readers`, and add it to the `BASE_READERS` inside `JsonReader`. Both I do with reflection, so code compatibility doesn't have to change. No other changes (pom.xml, groovy tests) left.

I had to remove my according test class, which is impossible to write without code base >=Java16.

**Pull request merged**
