### PR TITLE
#55 EnumSet not supported

### PR DESCRIPTION
**Pull request by francisu**

### CODE REVIEW

**Comment by francisu** [comment]
Thanks for the quick merge!

It turns out there is a case that's not handled having to do with a forward reference, but I'm having trouble creating a test case for it (I hit the problem in my code).  I will keep working at it and when I get it fixed, I will create another pull request.

**Comment by jdereg** [comment]
Francis, json-io 4.1.10 has been released.  It contains the EnumSet
support.  In addition, it has some additional enhanced support for custom
instantiators.

**Comment by francisu** [comment]
The problem I'm having is that the JsonObject of the enum value has a child of "ref" instead of the usual 2 values for the enum, which causes my code to resolve the enum to not work. It appears to be a forward reference to the enum which I can't seem to reproduce in a test case, and I'm not sure how to solve the problem in my solution. Any hints?

**Comment by jdereg** [comment]
The version I checked in 4.1.10 solves the issue you speak of, hence all
the additional change I made beyond the original pull request.  The
specific change that addresses the issue you are talking about, is that
enums are now treated as primitives, meaning they are never output using
the @id/@ref mechanism.  This is how Date, String, etc. are also treated.

**Comment by francisu** [comment]
Thanks so much! I just took the official version and verified that everything works on my end.

**Pull request merged**
