### PR TITLE
Direct object creation

### PR DESCRIPTION
**Pull request by KaiHufenbach**
Hi, thanks for your feedback. I have removed the dependency to sun.misc.*. I also tried to use the directInstanciation strategy only, but this will crash the VM under some cirumstances. Perhaps a property could be used e.g. "packagePrefix" to identify classes that can safely be direct instanciated.

### CODE REVIEW

**Comment by jdereg** [comment]
Kai, I received your latest pull request with changes for direct class instantiation using sun.misc.Unsafe.  In this particular change, I see a member variable in JsonReader:

private static Unsafe unsafe;

This reference, will require an import statement for sun.misc.Unsafe.  This direct reference needs to be avoided, as it creates a direct dependency on the Sun JVM in the json-io code.  

In order to do this, it would require using Class, Method, and invoke to 'communicate' with sun.misc.Unsafe without having direct references in the code.

For example, 

private static Object unsafe;

Notice that with this definition, I have a Object declared but not a direct reference to the class 'Unsafe' in the JsonReader code.  Next, to instantiate this class, I would need to do something like:

unsafe = Class.forName("sun.misc.Unsafe").newInstance();

This would get me an instance of the class, without a direct binding to the code.  The String reference 'sun.misc.Unsafe' in the code is OK.  An import statement reference, on the other hand, would be found during class parsing and throw a ClassNotFound error, or NoClassDef error when loading JsonReader if the code was running on a JVM that did not have the sun.misc.Unsafe code.

To use the 'unsafe' instance above, you would need to then locate the methods on the object using reflection, and then invoke those methods using .invoke().  This is harder to do that directly referencing Unsafe in the code, however, without doing this all through reflection, it creates a binding on sun.misc.Unsafe which json-io cannot have.

**Comment by KaiHufenbach** [comment]
Hi,

well.... I left the import out, because "Unsafe" is an inner-class wrapper,
declared in line 3414. With this wrapper, we can use Unsafe as declared in
"sun.misc.*", but we can change the way of acessing it, perhaps vm
specific, or even extend it.

I could have named it "OurUnsafe" or "WrappedUnsafe". But, as you see...
There should be no import and even no "NoClassDefFoundError" as I catch the
Exception on Instantiation.

Please correct me if I am wrong.

Cheers

Kai


2015-01-03 14:44 GMT+01:00 John DeRegnaucourt <notifications@github.com>:

**Comment by jdereg** [comment]
Kai, I have incorporated your changes.  I see that you have indeed entirely used reflection to create the Unsafe instance (nice work).  When I saw the class name 'Unsafe', I assumed it was sun.misc.Unsafe - not a static inner that you created.  My mistake.  

Before I release this code (it will be in json-io 2.8.0), I want to understand why the final 'Unsafe' attempt at object instantiation cannot always be used.  I would prefer to have this on by default, and even remove the 'switch' that controls it.

**Comment by KaiHufenbach** [comment]
Hey John,

thank you for merging. Well, that was my first idea, too.

Try to instantiate a ConcurrentHashMap using Unsafe -> Results in a
VM-Crash with thread-dump.
Try to instantiate an URL using Unsafe -> URL uses an in the declaration
initialized member called "helper", which is needed for functionality and
is normally not null, when instantiating the class. I havent found a
solution for initializing the class without invoking a constructor.

I found this out by trying your testsuite. This scared me a bit.

This leads to the following plan:  either a black-/whitelist which we
currently do not know or "scanning" the classfile for such situations or
using it as last dirty chance.


Cheers

Kai

2015-01-03 16:49 GMT+01:00 John DeRegnaucourt <notifications@github.com>:

**Pull request merged**
