### PR TITLE
Major (Minor) bugfixes

### PR DESCRIPTION
**Pull request by KaiHufenbach**
Hi,

we tried to integrate the latest version in our ecosystem, the following changes were needed to get it running.

- Source Bundles are now 'osgified' (Therefore only dots are allowed as separators in the version)
- Serialization with custom serializers now does not analyze objects which have a custom serializer
- Using custom deserializers was broken
- Fixed Testcases for using Custom De/Serializers

Cheers

Kai

### CODE REVIEW

**Comment by jdereg** [comment]
I don't believe I can merge the changes in (at least of them) because of the change to have the code not trace references on classes that have custom writers.  That change assumes that the entire subgraph has to be custom written, but that is not always the case.  I am pretty sure there are users who write part of the graph out in a custom format, but let it use the non-custom writers for 'deeper' parts of the subgraph.

I will have a certain answer on this within the next day or two.

**Comment by jdereg** [comment]
I have confirmed that indeed, the traversal for references must still happen for classes that have custom writers associated to them.  This is because the custom writer may delegate some of the work to classes it 'contains' and those may use the standard processing, and if so, need to properly connect references.

Also, it is ok for the createObjectInstance to create standard instances (the check for only creating if no custom writer breaks json-io for other users).

**Comment by KaiHufenbach** [comment]
To be more precise: We have the following problems:

- traversing an Object which has a custom writer throws exceptions (due to enhancement)
- it seems that a custom reader is not used, if "guessed" Object creation was successfull (refer to the test case).

Could you please have a deeper look on that problems?

**Comment by jdereg** [comment]
​Will do.​

**Comment by jdereg** [comment]
What exception is being thrown on the Object which has a custom writer?
Can you send me a stack trace?

**Comment by KaiHufenbach** [comment]
Ill try to do on Friday.
As I remember it throws an exception because an Object has the Interface
Iterable, but it is acutally not iterable at all.

Our object graph is very big, so thats why we use custom readers/writers.
Traversing the whole graph is not useful and takes a while...
And I am not sure how this works:

- a custom writer turns a huge object into an ID (primary key)
- the ordinary writers will try to add additional attributes, as the custom
writer is just used for the instance itself, not the children?!

Could please explain the idea behind that, I am currently lost....



Also please have a quick glance on my changes in CustomDataClass (+
corresponding reader):

This will let the test fail - but it should not, as there is a reader,
which knows how to treat the object creation correctly. - I used to have
such a test before to ensure that a custom reader is used.

2015-08-25 11:52 GMT+02:00 John DeRegnaucourt <notifications@github.com>:

**Comment by jdereg** [comment]
Kai,

CustomWriter's are used on a given class.  If a class has references to
other classes (working in the world of Graph's of objects, not
hierarchies), json-io cannot expect that the customer for a given class is
then used to write all references from the given class.  It can only be
used for the class it is associated to.  If a custom writer decides to
write more than a given classes values out (other referenced objects), it
can.  The other classes will still be traced (recorded) but that is
benign.  It is important that there are traced, because the custom writer
may need to determine whether to write a referenced class out or an @ref to
it, and to do that, the referenced class must be traced.

If you are not using 'instantiators' you should look into using that
feature of json-io.  That feature is what allows you to ensure that a given
class is correctly instantiated when the built-in newInstance() method
cannot instantiate a class.

**Pull request closed without merging**
